inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/**/*
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# "Missing top-level class documentation comment."を無効
Style/Documentation:
  Enabled: false

# "Line is too long"を無効
Metrics/LineLength:
  Enabled: false

# Metrics/LineLength のより良いデフォルト値を模索したい
 # https://github.com/rubocop-hq/rubocop-jp/issues/32
Metrics/LineLength:
  Enabled: false